### ISSUE TITLE
I2C only sends one byte

### ISSUE THREAD

**Issue by solexious** [energia/tivac-core#41]
I've been trying to control a pca9685 pwm ic over i2c on my tiva-c connected launchpad (129). I started off trying the adafruit library with Wire but had no luck.

Upon testing I found that I can only send one byte when sending a transmission. The following code should send 0x00 then 0x80 to address 0x40. (this will reset the pca9685)

```
#include <Wire.h>

void setup()
{
  Wire.setModule(0);
  Wire.begin();

  Wire.beginTransmission(0x40);
  Wire.write(0x00);
  Wire.write(0x80);
  Wire.endTransmission();
}

void loop()
{
}
```
Looking at the signals I get this:
![launchpadi2c](https://user-images.githubusercontent.com/249109/42292807-105934f8-7fcd-11e8-9a60-06175a04101f.PNG)

Where as if I use the same code (minus the setModule() ) on an arduino I get:
![arduinoi2c](https://user-images.githubusercontent.com/249109/42292818-2f83e8e6-7fcd-11e8-8f77-23122bc93faf.PNG)

I've tried putting delays between the Wire.write(), trying to write a string also just sends the first byte and nothing more.

Any ideas?

**Comment by solexious** [comment]
I did some more fault finding. I decided to try sending a data array and found that every 3rd byte actually gets sent, so when filling the buffer with 12 bytes, bytes 0, 3, 6 and 9 all get sent, but none of the ones in the middle. I'm not currently sure if the missing bytes aren't going in the transmit buffer, or aren't being correctly pulled from and sent from the buffer!

```
#include <Wire.h>

void setup()
{
  Serial.begin(9600);
  Wire.setModule(0);
  Wire.begin();

  
}

void loop()
{
  Wire.beginTransmission(0x40);
  uint8_t data[] = {0x00, 0x01, 0x02, 0x03, 0x40, 0x05, 0x06, 0x07, 0x08, 0x09, 0x10, 0x11};
  Wire.write(data, 12);
//  Wire.write(0x80);
  Serial.println(Wire.endTransmission());
}
```
![launchpadi2cbuffer](https://user-images.githubusercontent.com/249109/42296264-9b1c52dc-7feb-11e8-8478-be502cf1ca97.PNG)

**Comment by solexious** [comment]
So, progress!

I added a forced delay() between passing bytes to sendTxData inside Wire.cpp:

```
uint8_t TwoWire::endTransmission(uint8_t sendStop)
{
  uint8_t error = I2C_MASTER_ERR_NONE;

  if(TX_BUFFER_EMPTY) return 0;
  //Wait for any previous transaction to complete
  while(ROM_I2CMasterBusBusy(MASTER_BASE));
  while(ROM_I2CMasterBusy(MASTER_BASE));

  //Select which slave we are requesting data from
  //false indicates we are writing to the slave
  ROM_I2CMasterSlaveAddrSet(MASTER_BASE, txAddress, false);

  while(ROM_I2CMasterBusy(MASTER_BASE));
  unsigned long cmd = RUN_BIT | START_BIT;

  error = sendTxData(cmd,txBuffer[txReadIndex]);
  txReadIndex = (txReadIndex + 1) % BUFFER_LENGTH;
  if(error) getError(error);
  while(!TX_BUFFER_EMPTY) {
  	  delay(1); // *********** added delay ********************* //
	  error = sendTxData(RUN_BIT,txBuffer[txReadIndex]);
  	  txReadIndex = (txReadIndex + 1) % BUFFER_LENGTH;
	  if(error) return getError(error);
  }

  if(sendStop) {
	  while(ROM_I2CMasterBusy(MASTER_BASE));
	  HWREG(MASTER_BASE + I2C_O_MCS) = STOP_BIT;
	  while(ROM_I2CMasterBusy(MASTER_BASE));
	  currentState = IDLE;
  }
  else {
	  currentState = MASTER_TX;
  }

  // indicate that we are done transmitting
  transmitting = 0;
  return error;

}
```

This now correctly sends all bytes in the buffer (though with a large gap between them (trust me, its zoomed out, but all bytes in the buffer are now accounted for)):

![launchpadi2cbufferms](https://user-images.githubusercontent.com/249109/42298022-6e1581a4-7ffb-11e8-84a8-9e8bb36115ca.PNG)

so my guess is the part of the Wire lib that waits for the HW send buffer to be empty to put the next byte into is bugged and was trying to send too early, so was dropping bytes as a result. Will try to investigate further.

**Comment by krychlicka** [comment]
I dont know if is this the same problem but I had problems with hangs of MCU during random period of time (from minutes to half day) I have discovered that it is caused by I2C library, so I reverted to older version 1.0.2 of Wire.cpp which has added one more condition (see picture below). Now everything works OK,
![image](https://user-images.githubusercontent.com/47168017/52142727-c88adf80-2659-11e9-8bc0-b8686cb4fce2.png)

**Comment by solexious** [comment]
Thanks for the suggestion, will give it a try. Where did you find the previous version of the file? I was looking to see if it was a regression but couldn't find previous versions in the file history here.

**Comment by solexious** [comment]
I can't actually find these lines, could you link to the file and lines these are in?

**Comment by krychlicka** [comment]
I have no idea where get the link, I only downloaded support files for CC3200 via Board manager in Energia. I attached file (ver 1.0.2) located in energia-1.6.10E18\portable\packages\energia\hardware\cc3200\1.0.2\libraries\Wire\ and overwrite it to energia-1.8.7E21\portable\packages\energia\hardware\cc3200\1.0.3\libraries\Wire\
[Wire.zip](https://github.com/energia/tivac-core/files/2829410/Wire.zip)
I made it because except the condition mentioned abovew cpp file is equal.

**Comment by solexious** [comment]
Sadly I can't find a matching function in the tivac files. This code snippet seems to be unique to the cc3200 files.

**Comment by victorvasquez1507** [comment]
hi everyone!
I made changes to the Wire.cpp to actually work, these are the changes:
-The function ROM_I2CMasterBusy(MASTER_BASE) is broken so it's replaced according to ERRATA SPMZ850G (issue I2C#08) Texas Instruments, and since it is broken it works when it is placed in parts of the code where it should not be placed (this was also corrected).
-Fixed transmission according to ERRATA.
-Cleaning of buffers after an error in transmission is detected (ie. wrong slave address) that made necessary to send another transmission command for the i2c bus to send the right commands again.
-Fixed reception according to ERRATA.
-Fixed number of received bytes returned from "requestFrom()".
PS1: every modification has basic comments, but I'm uploading it for further use or collaboration from other developers.
The file is my repository and attached here. I have also already made a pull request to energia.
It is a work in progress and I hope it helps, and if anyone finds more bugs and how to solve them please feel free to make changes and update it.
[Wire.cpp.zip](https://github.com/energia/tivac-core/files/2881041/Wire.cpp.zip)

Regards.

**Comment by robertinant** [comment]
@victorvasquez1507 thank you for the fixes. I have applied them in master.
